create_learning_path:
  description: >
    Create a personalized learning path for the student based on their goals, current knowledge level, and learning style.
    The learning path should include:
    1. A clear progression of learning objectives
    2. Recommended resources and activities
    3. Assessment points to measure progress
    4. Estimated time requirements for each component
    5. A strategy for adjusting the path based on performance
    Use {subject} as the main learning area and consider {learning_style} as the student's preferred learning approach.
  expected_output: >
    A comprehensive learning plan with clear objectives, resources, activities, and assessment points that
    align with the student's goals and learning style. The plan should include a visual representation of the
    learning path and detailed descriptions of each component.
  agent: learning_journey_orchestrator
  dependencies: []

curate_learning_materials:
  description: >
    Research and compile the most relevant, high-quality learning materials for {subject} with a focus on {topic}.
    The materials should include a mix of:
    1. Academic sources (textbooks, journal articles)
    2. Interactive resources (videos, tutorials)
    3. Practical examples and case studies
    4. Supplementary materials for different learning styles
    Create concise summaries of each resource and explain how they connect to the broader learning objectives.
  expected_output: >
    A curated collection of learning materials with summaries, relevance ratings, and recommendations for 
    when/how to use each resource in the learning process. Include a concept map that shows connections 
    between different resources and topics.
  agent: content_curator
  dependencies: [create_learning_path]

create_assessment_plan:
  description: >
    Design an adaptive assessment strategy for {subject} that will:
    1. Establish baseline knowledge through initial diagnostics
    2. Provide regular knowledge checks with increasing complexity
    3. Adapt question difficulty based on student performance
    4. Identify specific knowledge gaps and misconceptions
    5. Measure both factual knowledge and conceptual understanding
    The assessments should align with the learning objectives identified in the learning path.
  expected_output: >
    A comprehensive assessment plan with sample questions at various difficulty levels, a system for analyzing
    responses, criteria for adapting difficulty, and metrics for measuring progress. Include instructions
    for generating new questions based on performance patterns.
  agent: assessment_engine
  dependencies: [create_learning_path]

develop_study_guide:
  description: >
    Create a conversational study guide for {subject} focusing on {topic} that:
    1. Explains core concepts in clear, accessible language
    2. Anticipates common questions and misconceptions
    3. Provides concrete examples and analogies
    4. Includes Socratic questions to deepen understanding
    5. Offers alternative explanations for difficult concepts
    The guide should match the student's {learning_style} and current knowledge level.
  expected_output: >
    A comprehensive study companion that can be used for reference and self-study. The guide should include
    explanations, examples, questions, and alternative approaches to help students understand difficult concepts.
    Format it as a conversational Q&A resource with rich examples.
  agent: study_buddy
  dependencies: [curate_learning_materials]

design_research_project:
  description: >
    Develop a structured research project for {subject} that will help the student practice essential research skills.
    The project should include:
    1. Guidelines for formulating a research question related to {topic}
    2. Research methodology appropriate for the subject area
    3. Strategies for finding and evaluating sources
    4. Methods for data collection and analysis
    5. Framework for presenting and discussing findings
    The project should be challenging but achievable given the student's current level.
  expected_output: >
    A comprehensive research project guide that walks students through each step of the research process with
    templates, examples, and evaluation criteria. Include tips for avoiding common pitfalls and strategies
    for developing critical research skills.
  agent: research_assistant
  dependencies: [create_learning_path, curate_learning_materials]

create_writing_assignment:
  description: >
    Design a writing assignment for {subject} with {topic} focus that will help students develop their writing skills.
    The assignment should include:
    1. Clear prompt and objectives aligned with learning goals
    2. Structured pre-writing activities (outlining, research)
    3. Guidelines for drafting, revision, and editing
    4. Rubric with specific criteria for evaluation
    5. Examples of strong writing in the relevant genre
    The assignment should challenge students while providing clear guidance.
  expected_output: >
    A complete writing assignment package with prompt, instructions, rubric, supporting materials, and a
    feedback framework. Include strategies for providing constructive criticism while maintaining the
    student's authentic voice and confidence.
  agent: writing_coach
  dependencies: [create_learning_path]

develop_project_plan:
  description: >
    Create a project management plan for a complex {subject} assignment related to {topic}. The plan should include:
    1. A project breakdown with clear milestones and deliverables
    2. A realistic timeline with buffer periods for unexpected issues
    3. Guidelines for time management and prioritization
    4. Strategies for monitoring progress and staying motivated
    5. Templates for planning, tracking, and reflection
    The plan should help students develop project management skills while completing their assignment.
  expected_output: >
    A detailed project management toolkit with templates, timeline, milestone tracking system, and
    accountability measures. Include contingency planning and strategies for overcoming common obstacles
    to project completion.
  agent: project_manager
  dependencies: [create_learning_path]

design_simulation:
  description: >
    Create an interactive simulation or scenario for {subject} that allows students to apply theoretical knowledge
    about {topic} in a practical context. The simulation should:
    1. Mirror real-world complexity and constraints
    2. Include decision points that require critical thinking
    3. Provide immediate feedback on choices and actions
    4. Scale in difficulty as students demonstrate mastery
    5. Connect explicitly to the learning objectives
    The simulation should be engaging while reinforcing key concepts from the curriculum.
  expected_output: >
    A detailed simulation design with scenario descriptions, decision trees, feedback mechanisms, and
    assessment criteria. Include guidelines for implementing the simulation and connecting it to other
    learning activities.
  agent: simulation_creator
  dependencies: [create_learning_path, curate_learning_materials]

integrate_learning_components:
  description: >
    Review all the components created by the educational agents and create a cohesive, integrated learning experience for {subject} focused on {topic}.
    The integration should:
    1. Ensure logical progression and connections between all components
    2. Identify and resolve any contradictions or gaps
    3. Create a unified narrative that carries through all materials
    4. Develop transitions between different learning activities
    5. Provide a master schedule that incorporates all elements
    The final product should feel like a seamless educational experience rather than separate components.
  expected_output: >
    A comprehensive learning experience blueprint that shows how all components work together to support
    learning objectives. Include a master schedule, integration points, and an overall narrative that
    connects all learning activities. The final product should be cohesive, engaging, and pedagogically sound.
  agent: learning_journey_orchestrator
  dependencies:
    [
      curate_learning_materials,
      create_assessment_plan,
      develop_study_guide,
      design_research_project,
      create_writing_assignment,
      develop_project_plan,
      design_simulation,
    ]
  output_file: personalized_learning_experience.md
